"$schema" = 'https://starship.rs/config-schema.json'

# add_newline = false
# scan_timeout = 10

# [character]
# success_symbol = "[\\$](bold green)"
# error_symbol = "[\\$](bold red)"
# vicmd_symbol = "[<](bold green)"

aws         = { disabled = true }
line_break  = { disabled = false }
package     = { disabled = true }
battery     = { disabled = true }
buf         = { disabled = true }
cobol       = { disabled = true }
conda       = { disabled = true }
crystal     = { disabled = true }
daml        = { disabled = true }
deno        = { disabled = true }
dotnet      = { disabled = true }
java        = { disabled = true }
julia       = { disabled = true }
kotlin      = { disabled = true }
localip     = { disabled = true }
hg_branch   = { disabled = true }
nim         = { disabled = true }
nix_shell   = { disabled = true }
ocaml       = { disabled = true }
openstack   = { disabled = true }
perl        = { disabled = true }
purescript  = { disabled = true }
rlang       = { disabled = true }
raku        = { disabled = true }
red         = { disabled = true }
singularity = { disabled = true }
spack       = { disabled = true }
swift       = { disabled = true }
vagrant     = { disabled = true }
vlang       = { disabled = true }
vcsh        = { disabled = true }
zig         = { disabled = true }

username    = { show_always = true }
